FROM php:8.3-apache
# Install required PHP extensions
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo pdo_mysql

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Inscrease memory limit
RUN echo "memory_limit = 512M" > /usr/local/etc/php/conf.d/memory-limit.ini

# Set correct permissions
RUN chown -R www-data:www-data /var/www/html

# Copy custom entrypoint script
COPY drupal-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/drupal-entrypoint.sh

ENTRYPOINT ["drupal-entrypoint.sh"]
CMD ["apache2-foreground"]

